### ISSUE TITLE
Intuitem Commercial License page is 404

### ISSUE THREAD

**Issue by skmeister** [intuitem/ciso-assistant-community#1096]
**Describe the bug**
The link to the intuitem Commercial License (https://intuitem.com/license/commercial/), which can be found in the [`LICENSE.txt`](https://github.com/intuitem/ciso-assistant-community/blob/main/LICENSE.txt) leads to a 404 page.
 
**To Reproduce**
1. Open `LICENSE.txt` to see the URL
1. Open https://intuitem.com/license/commercial/ in a browser

Shows a 404 page.

**Expected behavior**
A website with the license terms.

**Additional context**
I couldn't find the license anywhere on https://intuitem.com/, otherwise I would have created a PR to fix the URL.

(Unrelated: Thank you so much for CISO Assistant, you are awesome)

**Comment by ab-smith** [comment]
Thank you for the feedback and appreciation @skmeister ; the link has been fixed :)
Feel free to star the repo, join the Discord server and help spread the word 🤗
