### ISSUE TITLE
Mapping Frameworks

### ISSUE THREAD

**Issue by ab-smith** [intuitem/ciso-assistant-community#185]
- I want to do an assessment on one framework and automatically get my posture on another one 
- will be helpful to move from, let's say CSF to CMMC to assess the same project on a different scope
- will be helpful when a framework gets an upgrade to avoid redoing the assessment
- will be useful for reporting: I've just finished CSF assessment. How am I doing against ISO for instance?

Frameworks don't overlap necessarily, but if it can get half the work pre-done, it's a win

Multiple frameworks already have part of it done and we can improve that

**Comment by 42mst** [comment]
@ab-smith 
Yes makes sense. Are you planning to do it on a subset first? There are also ready-to-use mappings. I will list a couple of them in here:
[NIS2 - ISO 2.pdf](https://github.com/intuitem/ciso-assistant-community/files/15199081/NIS2.-.ISO.2.pdf)
[sp800-53r4-to-r5-comparison-workbook.xlsx](https://github.com/intuitem/ciso-assistant-community/files/15199083/sp800-53r4-to-r5-comparison-workbook.xlsx)
[Zuordnung_ISO_und_IT_Grundschutz.pdf](https://github.com/intuitem/ciso-assistant-community/files/15199084/Zuordnung_ISO_und_IT_Grundschutz.pdf)
[27002 2013 2022 Controls Mapping.xlsx](https://github.com/intuitem/ciso-assistant-community/files/15199086/27002.2013.2022.Controls.Mapping.xlsx)
[C5_2020_Referenztabelle.xlsx](https://github.com/intuitem/ciso-assistant-community/files/15199087/C5_2020_Referenztabelle.xlsx)
[Copy of CCF-VER2.xlsx](https://github.com/intuitem/ciso-assistant-community/files/15199088/Copy.of.CCF-VER2.xlsx)
[CyFun mapping Public_v20231106.xlsx](https://github.com/intuitem/ciso-assistant-community/files/15199090/CyFun.mapping.Public_v20231106.xlsx)

Doing this in combination with the #240 will be a gamechanger.

**Comment by ab-smith** [comment]
Hey, we will use the existing mappings as a starting point and keep the same approach of letting the community review and enrich them

**Comment by ab-smith** [comment]
@AndrzejRPiotrowski as a matter of fact, our recommendation is to have evidences attached to applied controls rather than the requirements and it will offers a better reusability and ease of mapping.
