### ISSUE TITLE
TPRM

### ISSUE THREAD

**Issue by ab-smith** [intuitem/ciso-assistant-community#212]
Third Party Risk Management

**Comment by cota44ur** [comment]
THank you Abder.
For information, both CESIN and CLUSIF are currently working on a Vendor or TPRM questionnaire based on ISO27001 chapters and ISO27002 security controls. If you are interested, tell me.

**Comment by ab-smith** [comment]
Absolutely, 
I was thinking about adding the one from VSA but if you have these we can definitely add them as a starting point :)

**Comment by eric-intuitem** [comment]
See #719 for data model evolution.
