### ISSUE TITLE
startup.sh: $'\r': command not found

### ISSUE THREAD

**Issue by laph95** [intuitem/ciso-assistant-community#243]
**Describe the bug**
docker-compose.sh executes and creates container into Docker Desktop, containing 3 images: caddy and frontend run well but backend image fails and gives logs attached. 
[ciso-assistant_docker_fail.log](https://github.com/intuitem/ciso-assistant-community/files/14946691/ciso-assistant_docker_fail.log)

**To Reproduce**
1. Execute docker-compose.sh 
2. See error

**Expected behavior**
All 3 images to run and application accessible at localhost:8443

**Screenshots**
![ciso-assistant_screenshot](https://github.com/intuitem/ciso-assistant-community/assets/53684589/9b272f93-5f2d-4847-acac-bcae7dd9e771)

**Environment (please complete the following information):**
 - Device: Laptop
 - OS: Windows 11
 - Docker Desktop v4.28.0

**Comment by Mohamed-Hacene** [comment]
Hi @laph95, I will try to reproduce your error and come back to you as fast as I can. I need to know if it's a global issue on windows or just in your case.

**Comment by laph95** [comment]
Thank you @Mohamed-Hacene. Actually I was wondering if the issue could come from using Docker Desktop... An additional point: doc states that credentials will be asked at a certain point during docker-compose.sh execution and I've never been asked.

**Comment by VigilantOps** [comment]
Hi,

the backend console shows this error :

```
startup.sh: line 3: $'\r': command not found
startup.sh: line 25: syntax error: unexpected end of file
```
After reforming the `startup.sh` script, it works for me.

**Comment by Mohamed-Hacene** [comment]
Hi @VigilantOps, thanks for sharing your solution. Could you show us what you've reformatted in the `startup.sh`?

**Comment by laph95** [comment]
Thank you very much @VigilantOps, I opened startup.sh script with Notepad and converted EOL to Unix in order to remove '\r'. Then it works as expected!

@Mohamed-Hacene: it would be great if you can help for the credentials, thanks.

**Comment by Mohamed-Hacene** [comment]
Here's a quick workaround once you've launched your container:
- retrieve the backend image ID 'ciso-assistant-community-backend' with the command `docker ps -a | grep backend` or via docker desktop
- use the command `docker exec -it <ID> python manage.py createsuperuser`, with the ID previously retrieved
- enter your credentials, which you can use immediately to log in

**Comment by VigilantOps** [comment]
@Mohamed-Hacene it seems to be an issue with the file encoding.

Github is referencing a configuration which can solve multi OS collaboration : [Configuring Git to handle line endings](https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings?platform=windows)

Maybe this can solve the issue in the future.

Regards,
