### ISSUE TITLE
Arabic translation

### ISSUE THREAD

**Issue by ab-smith** [intuitem/ciso-assistant-community#256]

**Comment by vishnudas327** [comment]
Hai

**Comment by AbdelatifAitBara** [comment]
Hi,

@ab-smith Could you please tell me your needs, I'm interested to contribute.
Best regards.

**Comment by nas-tabchiche** [comment]
I will notify you once #300 is merged, so that you can fork the repository

**Comment by AbdelatifAitBara** [comment]
Thank you for the explanation @nas-tabchiche, and OK, I'll wait for it.

**Comment by nas-tabchiche** [comment]
The pull request has been merged, feel free to go ahead with the translations! If you encounter any issues or have any questions along the way, please don't hesitate to reach out. I'll be glad to help.

**Comment by AbdelatifAitBara** [comment]
OK @nas-tabchiche, thanks for the information.
I'll start the translation, once I'm done the PR will be created :smile:

**Comment by ab-smith** [comment]
@AbdelatifAitBara, all good? feel free to reach out if you need assistance or more information 😊

**Comment by AbdelatifAitBara** [comment]
Hi @ab-smith,
Yea thank you, I'm doing my best to finish the translation ;) 
I'll try to finish it in this week.

![Screenshot from 2024-05-06 21-34-34](https://github.com/intuitem/ciso-assistant-community/assets/82835348/c53364c5-7a9f-4ef2-a30c-7da383b6e720)

**Comment by ab-smith** [comment]
it's ok, take your time, just wondering if we can help ;)
fyi: make sure to refresh your fork as we've pushed few things over the past 2 weeks :)
Thank you again!

**Comment by AbdelatifAitBara** [comment]
Hi @ab-smith,

We're almost there 💯 

![image](https://github.com/intuitem/ciso-assistant-community/assets/82835348/4cd21dbc-c988-4677-b2ad-64bc1d908a48)

**Comment by ab-smith** [comment]
Great @AbdelatifAitBara it’s highly expected and have been requested a lot lately :) 
let me know if it’s simpler for you that we push our arabic translation and you review it instead

**Comment by ab-smith** [comment]
we will have to review the UI afterwards for a better management of RTL languages, starting with the side menu and ModelTable,
@AbdelatifAitBara PR can give us more accurate wording on this basis afterwards
