### ISSUE TITLE
FedRAMP framework

### ISSUE THREAD

**Issue by AlexLaroche** [intuitem/ciso-assistant-community#260]

**Comment by ab-smith** [comment]
Will be added as two profiles: High and LI-SaaS.
This is another good case for the upcoming feature of multi-level frameworks that will improve this.

**Comment by ab-smith** [comment]
Ok, the framework is ready; we will merge #364 first to benefit from this flexibility of managing multiple levels instead of having three entries.

**Comment by ab-smith** [comment]
Merged. Will be available in next release.
