### ISSUE TITLE
Libraries improvements: custom one appearing in the imported libraries and be able to delete it

### ISSUE THREAD

**Issue by ab-smith** [intuitem/ciso-assistant-community#281]
**Problem statement**
Given that my custom library is not part of the standard store, it doesn't appear on the imported libraries but directly in the frameworks.

**Expected behavior**

Have them in dedicated section on frameworks management

**Additional context**
Thanks to Gildas for the feedback

**Comment by ab-smith** [comment]
Will be part of libraries management refactoring coming this week

**Comment by protocolpaladin** [comment]
Will it be retroactive on old personal libraries already integrated before the planned update?

Or is there a manual procedure to be followed if the library to be removed is on a production environment?

thank you for your work 🙂

**Comment by ab-smith** [comment]
Fixed in 1.3.5
