### ISSUE TITLE
ISO 31000 support?

### ISSUE THREAD

**Issue by ab-smith** [intuitem/ciso-assistant-community#285]

**Comment by eric-intuitem** [comment]
IS0 31000 provides principles and guidelines for risk management. It provides a comprehensive approach to identifying, analyzing, assessing, addressing, monitoring and communicating risks within an organization. It is not suitable for certification.
In the cyber domain, this umbrella standard gives rise to the ISO27001 standard, which is suitable for certification, and is already supported by CISO Assistant.
