### ISSUE TITLE
Ebios RM (ateliers)

### ISSUE THREAD

**Issue by ab-smith** [intuitem/ciso-assistant-community#286]
On dispose des objets pour gérer une analyse de risque et son plan de remediation mais il serait utile d'avoir des écrans supplémentaires pour gérer les ateliers

**Comment by protocolpaladin** [comment]
Tellement d'accord, clairement cette fonctionnalité open source de gestion complète d'analyse ebios RM de chaque atelier n'existe pas sur le marché réellement à ce jour. Ce serait une vrai plus value, très bonne idée et tellement hâte de pouvoir tester ça !

**Comment by ab-smith** [comment]
Questions à évoquer sur le live (prochainement) : 
- l’atelier 1, c’est finalement l’approche par conformité, donc la fonction audit de CA, est-ce suffisant ou il faudra une “vue” supplémentaire ?
- on revient au terme risque initial au lieu de risque courant pour homogénéiser ? On ne va pas créer la confusion avec le concept du risque inherent qu’on veut éviter ?
- rajouter un wizard pour enchaîner les ateliers ? On stock la progression client-side ? Dispatché sur nos objets ? Un nouvel objet ?

**Comment by protocolpaladin** [comment]
Y a pas que la conformité, faut définir la ou les missions et aussi les valeurs métier associés à chaque mission et ces valeurs métiers sont elles même rattaché à des bien support. Y a aussi la recherche d’événement redouté pour chaque valeur métier avec notion de Disponibilité Intégrité Confidentialité si on suis la norme et on peu aussi en profiter pour ajouter la tracabilite voila pour le premier atelier

**Comment by cota44ur** [comment]
Bonjour,
L'atelier 1 consiste aussi à recenser les valeurs métier et biens supports relatifs à l'objet de l'étude. Dans ce cadre il est possible d'associer ou ou plusieurs biens supports à une valeur métier.
La liste de bien support  pourrait être un framework sous format yaml dans les libs de CISO Assistant.

**Comment by ab-smith** [comment]
No, this is still ongoing. The is unrelated to treatment plan follow-up that is already available.

**Comment by ab-smith** [comment]
We're finally here, the preview is available in https://github.com/intuitem/ciso-assistant-community/releases/tag/v1.9.30
