### ISSUE TITLE
Observation not saved in associated requirement dialog

### ISSUE THREAD

**Issue by schmitz-ens** [intuitem/ciso-assistant-community#287]
When I enter an observation on an 'associated requirement' in 'compliance assessments,' and then click on 'Save,' the system responds 'The Requirement assessment object has been successfully saved,' but the observation is not actually saved.

**Expected behavior**
I expect the observation to be saved.

**Environment (please complete the following information):**

Client : 
 - OS: Linux
 - Browser : Chrome 122.0.6261.128

Server : 
- CISO Assistant Version: v1.0.8 Build: 07c5855
- Launched via Docker-compose from cisoassistant repo

**Comment by Mohamed-Hacene** [comment]
This problem should be fixed now with this [PR](https://github.com/intuitem/ciso-assistant-community/pull/297). Let me know here if it's ok on your side too, to close this issue.

**Comment by schmitz-ens** [comment]
Thx ! problem solved with Version:v1.1.0 Build:12e6bf2
