### ISSUE TITLE
No proper update of displayed 'Primary' fields in assets table

### ISSUE THREAD

**Issue by CyberPoly1000** [intuitem/ciso-assistant-community#294]
The 'Primary' label of primary assets, displayed besides the name of the asset does not get updated when moving to another page, where only Secondary assets are displayed (and thus no label at all should appear). 

1. Create one or more Primary assets
2. Create more than 10 other secondary assets (or less depending on the number of asset to display) in order to have at least 2 pages to be displayed
3. Go from one page to another and see the label appear next to secondary assets

Normally, the 'Primary' label should disappear next to secondary assets. 

**Screenshots**
![Screenshot_2024-04-19_13-59-42](https://github.com/intuitem/ciso-assistant-community/assets/52451277/61f5ee29-0614-4de6-9366-94649ad9caf2)
![Screenshot_2024-04-19_14-01-03](https://github.com/intuitem/ciso-assistant-community/assets/52451277/4033b609-a7cf-43e8-a6c4-f6966fda9cda)
![Screenshot_2024-04-19_14-01-22](https://github.com/intuitem/ciso-assistant-community/assets/52451277/4496178e-dbb7-4ed8-aed5-8a12ff091eb5)

 - Device: Virtual Box VM
 - OS: OpenSuse 15
 - Browser: Firefox
 - Version : 102.11.0esr

**Comment by Mohamed-Hacene** [comment]
This issue should be fixed now on main branch with PR #427
