### ISSUE TITLE
ISA/IEC 62443 Support

### ISSUE THREAD

**Issue by ab-smith** [intuitem/ciso-assistant-community#303]

**Comment by infosecmatters2021** [comment]
@ab-smith: The NIST CSF v1.1 shows the alignment with ISA 62443. Can this alignment information be used to add the framework to ciso assistant? If not, how would I show alignment using the NIST CSF framework (e.g., the concept of adding a tag like ISA 62443-3-3:2013 SR 7.8 or ISA 62443-2-1:2009 4.2.3.4)?

Excel spreadsheet link: https://www.nist.gov/document/2018-04-16frameworkv11core1xlsx
NIST CSF v1.1: https://www.nist.gov/cyberframework/csf-11-archive
