### ISSUE TITLE
Import backup issues

### ISSUE THREAD

**Issue by CyberPoly1000** [intuitem/ciso-assistant-community#305]
**Describe the bug**
Database is not loaded when JSON file is provided. 

**To Reproduce**
1. Export the DB in /backup-restore
2. Remove an item, for instance a threat
3. Import the previously exported DB 
4. The item you removed previously does not exist

**Expected behavior**
The imported database should match the exported one. 

**Additional context**
This error applies in local or in prod. In prod environment, there is even no redirection into the logging page, as in the local env.

**Comment by Mohamed-Hacene** [comment]
Hi @CyberPoly1000, thanks for the issue ! We'll will let you know once this one is fixed

**Comment by devoyon** [comment]
Had same issue from a fresh docker install on Ubuntu

- ciso assistant 1.1.1
- Build feb8456

I used the attached backup.
[ciso-assistant-db-2024-04-17T03_52_32.357Z.json](https://github.com/intuitem/ciso-assistant-community/files/15082782/ciso-assistant-db-2024-04-17T03_52_32.357Z.json)

**Comment by nas-tabchiche** [comment]
Hi,

Thank you for reporting the issue, this will be fixed with #315.

Best regards,
Nassim

**Comment by nas-tabchiche** [comment]
PR merged. Closing this
