### ISSUE TITLE
How to create credentials on the local instance when no prompt has been displayed at container startup

### ISSUE THREAD

**Issue by Mickind** [intuitem/ciso-assistant-community#307]
Hello, 
I don't know if this is the right section to ask you this information because I don't think it is a bug.

I would like to try to run the opensource application "CISO Assistant" on my PC. I installed it on docker using Docker Desktop for Windows. I followed the section in the guide called "Testing locally".

I would like to figure out how to register to the platform or where to enter the credentials directly into the code in order to log in.

![image](https://github.com/intuitem/ciso-assistant-community/assets/45635504/1615faff-f750-45b6-8da5-417228fb91f3)

Thank you very much in advance and I apologize if I should have the wrong section for opening the issue.

**Comment by ab-smith** [comment]
Hello @Mickind, 
Thanks for sharing. No need to apologise. It's better indeed to interact with the team for these requests on Discord but it's a good opportunity to pin the answer.
By following the steps and using WSL, I guess you triggered ./docker-compose.sh, did you get the prompt at the end of the script to enter an email and password for the 1st admin user? if not. that would explain your issue.
Regards,

**Comment by Mohamed-Hacene** [comment]
Hi @Mickind, 
In case you didn't get the prompt to create your admin account on your application, I refer you to this workaround, which will allow you to create a user on your local instance: https://github.com/intuitem/ciso-assistant-community/issues/243#issuecomment-2051428147

If you encounter any problems during handling, don't hesitate to come back to us - that's what we're here for :)

**Comment by Mickind** [comment]
> Hi @Mickind, In case you didn't get the prompt to create your admin account on your application, I refer you to this workaround, which will allow you to create a user on your local instance: [#243 (comment)](https://github.com/intuitem/ciso-assistant-community/issues/243#issuecomment-2051428147)
> 
> If you encounter any problems during handling, don't hesitate to come back to us - that's what we're here for :)

Thank you very much everyone, using this workaround now works!
Best regards.
