### ISSUE TITLE
Templates for Policies

### ISSUE THREAD

**Issue by ab-smith** [intuitem/ciso-assistant-community#312]
**Problem statement**

I want to be able to use CISO Assistant to create simple policies according to my context, and leverage the basics and best practices from the industry. It will be even better if the policy can automatically be mapped to risks and threats to benefit from CISO Assistant ecosystem.

**Expected behavior**

1. Go to the Governance section
2. Input some data about the organization, application, etc to customize the template 
3. Generate exportable PDF and keep them in my policies library 
4. I should be able to edit and update them afterward and keep simple versioning.

**Additional context**

Markdown should be more than enough for this.

**Comment by ab-smith** [comment]
Not expected that much by the community for now. Can be reopened later.

**Comment by sbe-arg** [comment]
This would be a nice feature to reconsider.
