### ISSUE TITLE
Add risk assessment not working

### ISSUE THREAD

**Issue by neocristal** [intuitem/ciso-assistant-community#313]
**Describe the bug**
crud.DcppG0_h.js:1  Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'map')

**To Reproduce**
1. Go to '[...](https://localhost:8443/risk-assessments)https://[localhost:8443/risk-assessments](https://localhost:8443/risk-assessments)'
2. Click on 'Add risk assessment'
const Re = ({objects: i, suggestions: e, label: s="name", value: l="id", extra_fields: t=[], self: r=void 0, selfSelect: a=!1})=>{
    const n = i.map(o=>({ <---- error
        label: t.length > 0 ? t.map(f=>ve(o, f)).map(f=>`${f}`).join("/") + "/" + o[s] : o[s],
        value: o[l],
        suggested: !1
    })).filter(o=>a ? !0 : o.value !== (r == null ? void 0 : r.id));
    if (e) {
        const o = e.map(N=>N[l])
          , f = n.filter(N=>{
            const G = o.includes(N.value);
            return G && (N.suggested = !0),
            !G
        }
        );
        return n.filter(N=>N.suggested).concat(f)
    }
    return n
}
**Expected behavior**
crud.DcppG0_h.js:1 
 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'map')
    at Re (crud.DcppG0_h.js:1:7485)
    at Array.Nl (ModelForm.ley4EG-F.js:1:34468)
    at Array.Ll (ModelForm.ley4EG-F.js:1:41463)
    at Tt (scheduler.DfDVByfk.js:1:994)
    at Ht (schemas.QZf0y17k.js:1:3693)
    at jt (index.CeLLYiwI.js:4:3960)
    at new xs (schemas.QZf0y17k.js:1:6040)
    at Vl (ModelForm.ley4EG-F.js:1:43190)
    at jt (index.CeLLYiwI.js:4:3960)
    at new yl (ModelForm.ley4EG-F.js:1:44927)
Re	@	crud.DcppG0_h.js:1
Nl	@	ModelForm.ley4EG-F.js:1
Ll	@	ModelForm.ley4EG-F.js:1
Tt	@	scheduler.DfDVByfk.js:1
Ht	@	schemas.QZf0y17k.js:1
jt	@	index.CeLLYiwI.js:4
xs	@	schemas.QZf0y17k.js:1
Vl	@	ModelForm.ley4EG-F.js:1
jt	@	index.CeLLYiwI.js:4
yl	@	ModelForm.ley4EG-F.js:1
y	@	CreateModal.DIcW4kVE.js:1
Y	@	CreateModal.DIcW4kVE.js:1
jt	@	index.CeLLYiwI.js:4
le	@	CreateModal.DIcW4kVE.js:1
re	@	scheduler.DfDVByfk.js:1
Qi	@	0.B-Y-C-F9.js:1
Ki	@	0.B-Y-C-F9.js:1
Me	@	0.B-Y-C-F9.js:1
Re	@	0.B-Y-C-F9.js:1
p	@	0.B-Y-C-F9.js:1
ht	@	scheduler.DfDVByfk.js:1
_t	@	scheduler.DfDVByfk.js:1
Promise.then (async)		
ut	@	scheduler.DfDVByfk.js:1
ht	@	index.CeLLYiwI.js:4
(anonymous)	@	index.CeLLYiwI.js:4
(anonymous)	@	0.B-Y-C-F9.js:1
u	@	index.CRdcE4fv.js:1
l	@	index.CRdcE4fv.js:1
trigger	@	stores.BbzDayGR.js:1
s	@	12.CVeID6-X.js:3

**Screenshots**
![12](https://github.com/intuitem/ciso-assistant-community/assets/1856664/3f7566bf-37ad-426b-8632-7ad8fabd45a7)

**Environment (please complete the following information):**
 - Device: [e.g. Notebook]
 - OS: [e.g. Windows 10]
 - Browser [e.g. EDGE]
 - Version [e.g. Version 124.0.2478.51 (Official build) (64-bit)]

**Additional context**

**Comment by ab-smith** [comment]
Thanks for sharing @neocristal. Have you done anything specific or it was a transient issue?
