### ISSUE TITLE
Backup & Restore: Backup not working (400 Error fetching the dump file)

### ISSUE THREAD

**Issue by joostdaem** [intuitem/ciso-assistant-community#318]
**Describe the bug**
When requesting a database backup: it returns "400 Error fetching the dump file". This is the case for the online "trial" version and the on-premise installed docker containers. On-premise uses a PostgreSQL database.

**To Reproduce**
1. Go to 'Extra -> Backup & Restore'
2. Click on 'Export database'
3. See error "400 Error fetching the dump file"

**Environment (please complete the following information):**
 - Browser Chrome & Safari
 - Latest version

**Comment by Mohamed-Hacene** [comment]
Hi @joostdaem, thanks for the issue. We also noticed this bug this morning, we'll let you know here once it is fixed.

**Comment by nas-tabchiche** [comment]
This is fixed with #320. This issue will be closed once PR is merged.
