### ISSUE TITLE
Individual Control Assignment

### ISSUE THREAD

**Issue by andersond952** [intuitem/ciso-assistant-community#338]
**Problem statement**
I want to be able to assign individual controls within a framework to different user within an organization.

**Expected behavior**
When a user logs in they could go to a view to see the controls they've been assigned rather than having to sift through the audit on their own. Person in charge of the audit would not have to keep up with who is responsible for tracking down each control.

**Comment by ab-smith** [comment]
part of Q2 roadmap indeed
