### ISSUE TITLE
inversion between planned and active in analytics

### ISSUE THREAD

**Issue by eric-intuitem** [intuitem/ciso-assistant-community#346]
**Describe the bug**
the histogram for planned and active applied controls in analytics is swapped.

**To Reproduce**
Create applied controls with planned and active status
**Expected behavior**
Histogram is correct.
**Screenshots**

**Additional context**
Reported by CG

**Comment by ab-smith** [comment]
Actually no inverted, it's the offset issue that we had on the audit status, trying something
