### ISSUE TITLE
Erreur traduction dans l'export html : status et attributs non traduits

### ISSUE THREAD

**Issue by protocolpaladin** [intuitem/ciso-assistant-community#351]
**Describe the bug**
Lors d'un export html d'audit avec l'interface en français et un document en français "Guide d'hygiène ANSSI". J’ai remarqué un bug de traduction quand on est en français les champs de couleur conforme, non conforme,etc sont en anglais au lien d'être en français.

**To Reproduce**
1. être avec l'interface en français
2. utiliser un audit français ou anglais ou autres
3. renseigner différent différent statut
4. Export

**Expected behavior**
Je m'attendais à ce que les champs renseigné dans le rapport exemple statut compliance s'affiche en français avec le mot conforme car mon interface est bien réglé en français et pas en anglais.

**Screenshots**

**Environment (please complete the following information):**

**Additional context**

**Comment by protocolpaladin** [comment]
Ce n'est pas lié au guide d'hygiène directement mais j'ai fait le test avec ce dernier

**Comment by ab-smith** [comment]
We need to pass the user locale to the export endpoint and either use the labels or a different base template per locale
