### ISSUE TITLE
Champs supplémentaires dans l'audit

### ISSUE THREAD

**Issue by protocolpaladin** [intuitem/ciso-assistant-community#352]
**Problem statement**

Demande d'ajout de fonctionnalité dans l'audit (champs: origine de l’écart et plan d’action avec une fonction dédié à la gestion de plan d'action)

Bonjour, je ne connais peut être pas encore bien l’outil. Mais lors d’un audit, exemple guide hygiène ANSSI ou autre, on sélectionne un statuts : à faire, en cours, non conforme, conforme, partiellement conforme, non applicable.

La partie observation est utile pour compléter les justifications. Cependant, je pense qui pourrait être intéressant pour l’utilisateur et l’auditeur de visualiser pour le motif partiellement conforme (la justification de cette écart) d’avoir un champ dédié supplémentaire nommé : origine de l’écart pour détailler vraiment la raison de l’écart.

Et de manière plus global en cas de non conformité ou partiellement conforme ajouter aussi un champs dédié plan d’action (avec possibilité de planifier date et rappel en plus) qui servirait à justifier  ce qui est prévu pour corriger la non conformité ou compléter la mesure partielle et ainsi avoir un vrai suivit et plan d’action aussi pour l'utilisateur dans le même outil et même par la suite générer une page de plan d’action et un export.

Quand pensez vous ?

**Comment by ab-smith** [comment]
Bonsoir @protocolpaladin ,
en fait les applied controls (mesures appliquées si t'es en FR) sont pensés pour ça justement, en gros c'est la mesure de sécurité (donc l'action) qui sera attachée à un item de l'audit ou à une analyse de risque et qui aura justement ces attributs.

L'avantage de ce découplage est qu'on peut faire un mapping n à m réutilisable facilement : une mesure peut couvrir plusieurs points de l'audit et une exigence de l'audit peut être attachée à plusieurs mesures, et surtout qu'on peut reprendre les mesures entre différents audits.

Tu vois l'idée ? C'est un peu ce que tu avais en tête ?
 
Il manquerait en effet une visu agrégée pour avoir la synthèse des actions liées à un audit, comme ce qu'on a pour l'analyse de risques

**Comment by protocolpaladin** [comment]
Oui je vois dans ce cas dans la mesure appliqué le champ description regroupe un peu tout. Il arrive que parfois les mesures soient déjà connues comme partielle. Dans ce cas peut être ajouter une notion de gestion applique partiellement ou complètement et dans le cas de partiellement obliger un champ supplémentaire pour justifier les écarts. Et après dans l’audit map si partiellement on peut pas mettre conforme mais seulement en cours ou partiellement conforme. Et comme tu disais par la suite intégrer en map ces champs dans la vue d’audit ?

une idée alternative quand penses tu ?

**Comment by ab-smith** [comment]
Sera traité par les commentaires en timeline sur les requirements et les risques
