### ISSUE TITLE
 BSI minimum standard for the use of external cloud services (MST_NCD) Controls

### ISSUE THREAD

**Issue by 42mst** [intuitem/ciso-assistant-community#359]
Provide BSI minimum standard for the use of external cloud services (MST_NCD) Controls.

[mst_ncd-2020-de(4).xlsx](https://github.com/intuitem/ciso-assistant-community/files/15199159/mst_ncd-2020-de.4.xlsx)
[mst_ncd-2020-en.xlsx](https://github.com/intuitem/ciso-assistant-community/files/15199160/mst_ncd-2020-en.xlsx)

@ab-smith 
Needs to have framework tag

**Comment by ab-smith** [comment]
Covered in #935
