### ISSUE TITLE
Copy the items of a risk assessment or an audit for a new one

### ISSUE THREAD

**Issue by CyberPoly1000** [intuitem/ciso-assistant-community#376]
**Problem statement**
I would like to be able to copy the items of a risk assessment or of an audit in order to perform a similar one after some time. For instance, each year I have to reproduce a risk assessment. After one year, some risks are the same but just need a re-evaluation. In order to avoid the waste of time for re-encoding every previously encoded risks, this feature could be a life-saver. A way to distinguish new risks, deleted risks, modified risks and already encountered risks could be great, so that we keep track of what have changed since last time. 

The same approach could be done for audits (e.g. ISO27k that renews every 3 years).

**Expected behavior**

1. Go to 'Risk assessments'
2. Click on 'Add risk assessment'
3. In the pop-up window, ask the choice for reusing old risk assessment (either in review, done or deprecated) : also nice to have, the possibility to chose another risk matrix
5. The new risk assessment is created, with all the risks levels reassigned to NULL
6. For new risks, add a label 'New'
7. For modified risks (i.e. risks that do not have the same risk level), add a label 'Modified' or 'Updated' 

The same behavior can be translated to audits (even though not that trivial)

**Comment by ab-smith** [comment]
Covered in #185 that got merged today.
