### ISSUE TITLE
Inaccurate status of applied controls in Analytics dashboard

### ISSUE THREAD

**Issue by CyberPoly1000** [intuitem/ciso-assistant-community#377]
**Describe the bug**
In Overview -> Analytics -> Risk, the 'Applied controls status' chart displays the wrong status of my applied controls. I have 121 active applied controls, still the cart indicates they are all inactive. 

**To Reproduce**
1. Go to Overview -> Analytics -> Risk
2. Check 'Applied controls status' chart
3. See that the status displayed is not the same as the real status of your controls

**Expected behavior**
Display the proper status

**Screenshots**
![image](https://github.com/intuitem/ciso-assistant-community/assets/52451277/7ff62741-3460-4b85-a0a3-2a5c634906a8)
![image](https://github.com/intuitem/ciso-assistant-community/assets/52451277/0594f277-3b1c-42fc-a035-9e959798ce7c)

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser: Brave
 - Version of CISO : 1.2.3 build 0bacb25

**Comment by ab-smith** [comment]
Fixed in #346, will be available in the next release
