### ISSUE TITLE
Feature to directly edit a risk scenario after creation

### ISSUE THREAD

**Issue by CyberPoly1000** [intuitem/ciso-assistant-community#378]
**Problem statement**
It is not possible to directly edit a risk scenario after the pop-up window has been filled. 

**Expected behavior**

1. Create a risk assessment
2. Create a new risk scenario
3. Fill the pop-up window
4. Fill a checkbox 'Directly edit' to be redirected to the Edit page of the scenario
5. Click on 'Save'
6. Edit the risk scenario directly

**Additional context**
For the moment, when the 'Save' button is clicked, we stay on the Risk Assessment and we have to go to the risk scenario and click 'Edit'. It is not that user-friendly when having a lot of scenarios and especially when we already want to edit it.

**Comment by ab-smith** [comment]
Not scheduled, as most users appreciate the fact that we capture the idea and enrich it later and this would affect that. we might revisit this later as an alternative option.
