### ISSUE TITLE
Approver gets 403:Forbidden when accepting or rejecting owned Risk Acceptance

### ISSUE THREAD

**Issue by CyberPoly1000** [intuitem/ciso-assistant-community#386]
**Describe the bug**
I have a risk assessment in a group 'Global/Security' containing a test scenario. A risk acceptance is created for the test scenario contained in the risk assessment. The approver can see the action boxes to Accept or Reject the risk acceptance but nothing happens. In the backend logs, I see a 403 response for the action. 
I tested with the accept and reject button, same output in the logs. 
I tested by granting 'Global - Approver' status only to the approver AND with 'Security - Approver' status as well. Same output in the logs. 

**To Reproduce**
1. Login as global admin
2. Create a risk assessment
3. Create a risk scenario
4. Go to Risk acceptance and create a risk acceptance containing the test scenario
5. Log in as the approver 
6. Go to risk acceptance and select the test risk acceptance previously created
7. Select 'Validate' or 'Reject' action button
8. See the 403 response in backend logs

**Expected behavior**
The risk acceptance should be validated or rejected.

**Screenshots**
https://github.com/intuitem/ciso-assistant-community/assets/52451277/1cdfe8e4-fe18-4adb-9f05-58262e1731f8

![image](https://github.com/intuitem/ciso-assistant-community/assets/52451277/91a9353b-9181-4fe6-a29d-83ede76282b2)

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser: Brave
 - Version: 1.2.3 build 0bacb25

**Comment by ab-smith** [comment]
@eric-intuitem looks like a regression

**Comment by nas-tabchiche** [comment]
Hi @CyberPoly1000, onto which folder is the acceptance attached?
