### ISSUE TITLE
Implementation groups are (wrongly) translated during selection

### ISSUE THREAD

**Issue by eric-intuitem** [intuitem/ciso-assistant-community#398]
**Describe the bug**
When using French language, and selecting an implementation group for e.g. Fedramp, some IGs are wrongly translated:
Low -> Faible
Moderate is not translated
High -> Haut

**To Reproduce**
Use Fedramp with French interface

**Expected behavior**
No translation at all.

**Comment by ab-smith** [comment]
the model is sending the right labels, for some reason it's the component that is translating the strings while it should just render them,
<img width="1098" alt="image" src="https://github.com/intuitem/ciso-assistant-community/assets/11318384/9adb9f35-3b57-4c42-a265-8625dcf108fe">
