### ISSUE TITLE
Cmd-k and Keyboard shortcuts

### ISSUE THREAD

**Issue by ab-smith** [intuitem/ciso-assistant-community#405]
We can start with simple ones like the ones on Github for main screen to have less clicks:
<img width="556" alt="image" src="https://github.com/intuitem/ciso-assistant-community/assets/11318384/15b73079-e029-4ec3-863e-b010fce92185">

and then move to a command palette later on (cmd-p / cmd-k / ctrl-p style) 😊

**Comment by nas-tabchiche** [comment]
This would indeed be a great addition. Here are some promising implementations to study:

- https://github.com/rohitpotato/svelte-command-palette
- https://github.com/huntabyte/cmdk-sv
- https://github.com/Abdulmumin1/kbar-svelte-mini
