### ISSUE TITLE
ANSSI Hygiene Measures Incorrect Measure Order

### ISSUE THREAD

**Issue by EvoXCX** [intuitem/ciso-assistant-community#419]
**Describe the bug**
Hello,
Not really a bug but rather a display problem, In section VI the conformity 27 is under 28 and 29 measures.

**To Reproduce**
1. Download referential
2. Create an Audit with ANSSI Hygiene Measures
3. Scroll down to VI section
4. Measure 27 is under 28 & 29

**Expected behavior**
Measure 27 under 28 and 29

**Screenshots**
![image](https://github.com/intuitem/ciso-assistant-community/assets/25347475/442ab149-2a27-45fe-b10d-fe9140ae3b7e)
![image](https://github.com/intuitem/ciso-assistant-community/assets/25347475/d7e6a3b2-5324-4b3a-8959-7bcd80d91e1b)

**Environment (please complete the following information):**
 - Device: Virtual Server
 - OS: Debian12
 - Browser Edge, Firefox
 - Version Edge: 124.0.2478.80, Firefox: 125.0.3

When I look at the [XLSX](https://github.com/intuitem/ciso-assistant-community/blob/main/tools/anssi/anssi-guide-hygiene.xlsx) where populating CISO Assistant there is no error (I didn't see any problem)

**Comment by ab-smith** [comment]
Hello @EvoXCX and thank you for reporting this,
I can't reproduce the issue 
<img width="1108" alt="image" src="https://github.com/intuitem/ciso-assistant-community/assets/11318384/22efb377-e0a5-40a2-8369-602fec68a505">

can you share which CISO Assistant version you're using?
<img width="318" alt="image" src="https://github.com/intuitem/ciso-assistant-community/assets/11318384/d4063c01-7491-42a4-8adf-2748b4739257">

**Comment by EvoXCX** [comment]
Ok, this is probably a problem on my side, thanks 😄 

P.S: @ab-smith Very good presentation of the CISO assistant with BE-CYBER, I look forward to the next interviews.

**Comment by ab-smith** [comment]
Thank you very much @EvoXCX ! The next one is this week indeed 🤗

If not done already, don't forget to star the project to get all the updates 🚀

(PS: I see item 29 repeated in your screenshot indeed; it could be some local visual glitch, let me know afterward on Discord if it's persistent to investigate more)

**Comment by EvoXCX** [comment]
Don't worry item 29 is not buggy just made appeared 2 times in my screenshots to understand correctly that is under item 29.
