### ISSUE TITLE
Informations Disclosure on Main Dashboard ?

### ISSUE THREAD

**Issue by EvoXCX** [intuitem/ciso-assistant-community#421]
**Describe the bug**
Example Context:
I created a domain with name Domain1 and one user in this group as Domain Administrator.

I created a new domain with name Domain2 and one user in this group as Domain Administrator.

Then I created an Audit on theses 2 domains.

And when I connect with one of theses account I see on Analytics Dashboard certain informations that is not in actual domain.

**Expected behavior**
Admin from Domain2 can only see his assignment and same for the Admin from Domain1

**Screenshots**
Admin1 in group Domain1 with all audit and risk assessment
![image](https://github.com/intuitem/ciso-assistant-community/assets/25347475/315a0453-d985-44c1-9858-5151b08ca45e)
![image](https://github.com/intuitem/ciso-assistant-community/assets/25347475/cda29597-ce1b-4a09-a22f-abefd5363e64)
![image](https://github.com/intuitem/ciso-assistant-community/assets/25347475/1565f670-5f7d-4d2c-9021-bd94e44bde34)

Admin2 in group Domain2 with only 1 audit created
![image](https://github.com/intuitem/ciso-assistant-community/assets/25347475/f9e1c2aa-1c2e-43bc-a6b5-2789cfe9a065)
![image](https://github.com/intuitem/ciso-assistant-community/assets/25347475/f93e6eb1-bed7-4a60-a494-1cfeafe0d803)
![image](https://github.com/intuitem/ciso-assistant-community/assets/25347475/6f4b7440-a9a6-4839-aedb-0df35dd6112d)

**Environment (please complete the following information):**
 - Device: Virtual Server
 - OS: Debian 12
 - Browser Edge, Firefox

Maybe it's normal that Dashboard use data from all domains, but it will be fine if we can separe into more little team that do not need to see certain parts.

**Comment by Mohamed-Hacene** [comment]
Hi @EvoXCX,

Thanks for this issue, we've noticed this too and are in the process of correcting it. I'll link the pull request to your problem when I push it so that you can follow its progress and test it for your specific application.
