### ISSUE TITLE
languages should not be translated

### ISSUE THREAD

**Issue by eric-intuitem** [intuitem/ciso-assistant-community#425]
**Describe the bug**
the list of selectable languages should not be translated, or at least the original name shall be shown also.

**Expected behavior**
Each language name should stay in its own language, thought the translation can be displayed too (that's what MacOS is doing).
E.g. if we are currently in English:
Français (French)
عربي (Arabic)

**Comment by ab-smith** [comment]
ok with the recent flag introduced in #411  it would be possible
