### ISSUE TITLE
Add sector(s) for libraries

### ISSUE THREAD

**Issue by eric-intuitem** [intuitem/ciso-assistant-community#430]
**Problem statement**
I want to easily filter all libraries related to a specific sector, like automotive or aerospace.

**Expected behavior**

Add a sector or a list of sectors to each library, and allow selection by sector.

**Comment by nas-tabchiche** [comment]
Can't this be addressed using tagging? See #413

**Comment by ab-smith** [comment]
Duplicate with #413
