### ISSUE TITLE
Slow App + Evidence Attachment problem

### ISSUE THREAD

**Issue by EvoXCX** [intuitem/ciso-assistant-community#432]
**Describe the bug**
Hello,
I can't upload attachment to evidences, I think the problem is more deeper than that because web pages take very long time to load, maybe this is a problem with reverse proxy but can't figure what cause this problem.

No error log in backend and frontend containers only this line:
```shell
2024-05-15T14:36:50.751043Z [info     ] request_finished               [django_structlog.middlewares.request] ciso_assistant_url=https://ciso.domain.com code=200 ip=172.24.0.4 request=GET /api/requirement-assessments/ request_id=560050e9-334c-4f2a-ad83-266e8ad82ad6 user_id=4194dd0e-7645-4671-a86d-2e5894caab29
```

**To Reproduce**
1. Go to "Evidences"
2. Click on "Evidence Item"
3. Add attachment to evidence
4. No error on GUI side and CLI side
5. WWebpage don't react (Need to reload or back)

**Expected behavior**
Attachment upload to selected evidence

**Environment (please complete the following information):**
 - Device: Virtual Machine
 - OS: Debian12
 - Browser Edge, Firefox

**Additional context**
Maybe my slow app cause problem to upload dunno why is so slow and in your demonstration application goes fast.

**Comment by ab-smith** [comment]
Hello @EvoXCX, thanks for the feedback.
Can you please share which version you're using and the virtualisation setup that you have?
Thank you

**Comment by EvoXCX** [comment]
I use latest version 1.3.3, my virtual machine is under VMWare ESXI.
OS is Debian 12 with Docker 26.1.2, using Docker CLI wit compose to up containers.

**Comment by NaschR** [comment]
Same problem for us the app is very slow when requesting change in DB or sign in

**Comment by ab-smith** [comment]
@EvoXCX  and @NaschR  I believe that both of you are using postgre instead of sqlite, nginx instead of caddy and virtualisation on ESXi instead of Proxmox ?

**Comment by ab-smith** [comment]
Also, what resources have you allocated to the VM, please?
The minimum requirements are 2 cores and 2 Gi Memory

**Comment by NaschR** [comment]
i'm using Sqlite, caddy and ESXI, resource are 3 core and 3 gig of rams

**Comment by EvoXCX** [comment]
I'm using SQLite, Nginx and ESXi, with 4 cores and 6Go RAM

**Comment by ab-smith** [comment]
Ok so you both have ESXi and nginx in common; I doubt that ESXi is doing something special here, so let me add an nginx and see how it goes,
Theoretically, we should not chain reverse proxies but let’s see

**Comment by NaschR** [comment]
I don't have Nginx personnaly

**Comment by ab-smith** [comment]
it's regarding your previous message about an extra proxy
> "but we have a proxy in front of everything to be able to access it from outside"

**Comment by ab-smith** [comment]
we've made significant performance improvements with version 1.4.2 please try it out and let us know. thank you

**Comment by ab-smith** [comment]
hello @EvoXCX thanks for testing,
are you sure you've update to the latest version, right?

**Comment by EvoXCX** [comment]
Yes
![image](https://github.com/intuitem/ciso-assistant-community/assets/25347475/9ffbff48-4a40-4148-a302-4e2528768886)
