### ISSUE TITLE
ASVS: include the levels using implementation groups

### ISSUE THREAD

**Issue by CyberPoly1000** [intuitem/ciso-assistant-community#438]
**Problem statement**
In some frameworks (for instance Cyber Fundamentals in Belgium, ASVS from OWASP), depending on the maturity of the company, it is possible to select one level of complexity of the framework. By default in actual implementation, the max level of complexity is considered, as it usually comprises every controls of the framework. 
It would be easier in some cases to allow the user to select the level of complexity of the framework to fit its needs as well as saving some time. 
There are several solutions for this. The easiest (from my perspective) is to integrate in the JSON definition of the framework an attribute 'complexity' that defines the different levels and the related non-applicable controls (therefore, the max level complexity does not define any of these controls). When selecting the framework for an audit for instance, the user selects the complexity needed and the N/A controls are automatically filled in.

**Expected behavior**

1. Go to 'Audit'
2. Select 'New audit'
3. Select the framework needed for the audit
4. If the JSON definition contains the attribute 'complexity', then display the defined levels
5. Depending on the chosen level, pre-fill the N/A controls as defined in the JSON

**Additional context**
ASVS contains three levels : L1, L2 & L3 (see https://owasp.org/www-project-application-security-verification-standard/). The following JSON would be used : 
```
[...]
"complexity": {
    "L1": {
        "V1.1", "V1.2", [...]
    }
    "L2" : {
            [... N/A controls for L2]
    }
    "L3" : {}
}
[...]
```

**Comment by ab-smith** [comment]
Hello @CyberPoly1000,

I believe this is covered with the concept of implementation groups that we've released last week (version 1.3.x). Take a look at this page: https://intuitem.gitbook.io/ciso-assistant/features-highlights/multi-level-support

Is this what you had in mind?

**Comment by ApcmJBld** [comment]
Hi @ab-smith,

Yes it is, indeed. I did not call it this way in my mind, this is why I did not look at it.
However, not all the frameworks support the implementation groups (for instance ASVS). Should I raise another dedicated feature request?

**Comment by CyberPoly1000** [comment]
Hi @ab-smith,

Yes it is, indeed. Thank you ! It was not the same name in my mind, so I did not look at it. 
However not every framework has an implementation group (for instance, ASVS). Should I raise a dedicated feature request ? 

Thanks

**Comment by ab-smith** [comment]
You're right; as mentioned in the doc, we haven't propagated this new feature on all compatible libraries yet, but the top 5 requested.  Changing the ticket title to reflect the case of ASVS.

**Comment by ab-smith** [comment]
Merged @CyberPoly1000 . will be available in the next release 🤗
