### ISSUE TITLE
Problème export  et preuve et mesure associé

### ISSUE THREAD

**Issue by protocolpaladin** [intuitem/ciso-assistant-community#439]
**Describe the bug*
L’ajout d’une mesure appliquée associé à une évaluation d’audit n’intègre pas la preuve automatiquement associé dans la partie preuve et aussi l’export du rapport exporte autant de pièce jointe pour une même mesure appliqué avec preuve  ou preuve ajoute identique ajoutée manuellement. Et si plusieurs évaluations audits sont justifier par une même mesure ou preuve lors de l’export ces fichiers sont exportés plusieurs fois et crée un export conséquent en taille alors qu’on utilise le ma même mesure ou preuve plusieurs fois exemple pssi charte.

**To Reproduce**
Faire plusieurs évaluations d’audit  d’un framework et associé une à plusieurs mesure similaire déjà associé à des preuves répéter pour chaque évaluation et ajouter les preuves identiques manuellement.

et exporter

**Expected behavior**

Lors de l’ajout d’une mesure avec preuve associé la reporter automatiquement dans la partie preuve.

lors de l’utilisation d’une même mesure ou preuve pour une même évaluation ou plusieurs évaluation n’exporter qu’en seul fois le fichier dans l’export.

**Comment by protocolpaladin** [comment]
bonjour @Mohamed-Hacene merci pour le retour.

suggestion :
Cela induit en erreur le fait qu’une preuve associé à une mesure ne soit pas tag dans la partie preuve nativement je trouve d’où la remontée et je pense que tag automatiquement la preuve ou afficher clairement dans l’application les mesure avec preuve sont automatiquement incluses et qu’il n’y a pas besoin de les rajouter empêcherai de se poser la question et d’autre ticket à venir peut être.

**Comment by Mohamed-Hacene** [comment]
Effectivement, je comprends mieux votre remarque. Je prends note de cela et nous verrons comment améliorer l'ergonomie des preuves associées à une exigence.

Une fois le problème de duplication des preuves dans le rapport réglé, je laisserai cette issue ouverte pour garder une trace de cette demande et que vous soyez notifié lorsque nous travaillerons dessus, pour éventuellement avoir un avis externe. 

Merci beaucoup pour votre retour !

**Comment by protocolpaladin** [comment]
Toujours le même problème d’après mes tests (j’ai build localement la version main actuel du git)

2 évaluations dans un même audit avec mesure et preuve similaire et 4 fois la même PJ dans l’export zip

**Comment by Mohamed-Hacene** [comment]
D'accord, c'est étrange je n'arrive plus à reproduire ce comportement pourtant je sais que ça m'est également arrivé juste avant que vous reportiez cette issue. 

Pouvez-vous me préciser quel framework et quel type de preuve vous avez utilisé pour que je reproduise à l'identique votre use case ?

**Comment by protocolpaladin** [comment]
Norme iso version français avec .docx mais pareil également avec pdf ou image sur les premiers tests à l’ouverture de ce PR.

**Comment by Mohamed-Hacene** [comment]
Ok @protocolpaladin, I did not reproduce the error (because we have different environments) but I think I found an inconsistency that should be the cause of this issue.

Could you try to export your audit on the last PR #480 I linked ?

**Comment by protocolpaladin** [comment]
Toujours le même problème d’après mes tests en rebuild le git main dans sa version actuelle

**Comment by Mohamed-Hacene** [comment]
Sur main c'est normal, la branche n'a pas été poussée encore. Si vous n'avez pas la capacité de tester sur la branche, je reviendrai vers vous pour que vous testiez quand nous aurons mis main à jour. 

Encore merci pour ce feedback !
