### ISSUE TITLE
Problem with login

### ISSUE THREAD

**Issue by PaulinDeuxTrois** [intuitem/ciso-assistant-community#440]
**Describe the bug**
When i enter wrong credentials, i have the "Unable to login with provided credentials" which is expected but when i use the super login created in docker-compose.sh, the form clears himself and i get to /login?next=/analytics (i was at /login?next=/ before). I also see the 200 for my login post but the requests coming after have none user id. 

**To Reproduce**
1. ./docker-compose.sh
2. Create superlogin in script
3. Try to login with it

**Expected behavior**
Login and access to Ciso

**Screenshots**
Here is my backend log. I think it might be from the user_id equals to none in requests after login  : 

![Capture d'écran 2024-05-16 140838](https://github.com/intuitem/ciso-assistant-community/assets/95508677/77cff82f-50cc-4b0f-a84e-2efda26d27ec)

I also have my frontend log : 

![Capture d'écran 2024-05-16 140741](https://github.com/intuitem/ciso-assistant-community/assets/95508677/963c76f7-d98e-4c5d-aea6-f44ce81dc842)

**Environment (please complete the following information):**

 - VM proxmox running debian 12
 - all browser i tried (edge, brave, chrome) 

**Additional information**

This is the docker-compose.yml i use, i might have misconfigured something :

version: "3.9"

services:
  backend:
    container_name: backend
    image: ghcr.io/intuitem/ciso-assistant-community/backend:latest
    restart: always
    environment:
      - ALLOWED_HOSTS=backend
      - CISO_ASSISTANT_URL=http://caddy:5173
      - DJANGO_DEBUG=True
    volumes:
      - ./db:/code/db

  frontend:
    container_name: frontend
    environment:
      - PUBLIC_BACKEND_API_URL=http://backend:8000/api
      - PROTOCOL_HEADER=x-forwarded-proto
      - HOST_HEADER=x-forwarded-host

    image: ghcr.io/intuitem/ciso-assistant-community/frontend:latest
    depends_on:
      - backend

  caddy:
    container_name: caddy
    image: caddy:2.7.6
    restart: unless-stopped
    ports:
      - 5173:5173
    command:
      - caddy
      - reverse-proxy
      - --from
      - http://my_ip:5173
      - --to
      - frontend:3000
    volumes:
      - ./db:/data

**Comment by eric-intuitem** [comment]
I recommend several fixes:
- CISO_ASSISTANT_URL=https://caddy:8443
- Ports for Caddy should be 8443:8443
- --from in caddy container should point to https://caddy:8443
- Add -i in caddy container to generate a local certificate.

**Comment by PaulinDeuxTrois** [comment]
Thank you, all is good now.
Have a nice day
