### ISSUE TITLE
Bad rendering of risk matrix legends in risk assessment report

### ISSUE THREAD

**Issue by CyberPoly1000** [intuitem/ciso-assistant-community#446]
**Describe the bug**
The PDF rendering of the risk matrix legends at the end of the risk assessment report is faulty. 

**To Reproduce**
1. Go to 'Risk assessment'
2. Add several risk scenarios to have a large risk matrix
3. Export the risk assessment as a PDF
4. Go all the way down the report and see the matrix

**Expected behavior**
Legends should be properly aligned and displayed

**Screenshots**
![image](https://github.com/intuitem/ciso-assistant-community/assets/52451277/9f52d339-30d1-4a9b-91ba-d70b39b08478)

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser: Brave
 - Version: v1.3.4 build 6a398d9b

**Comment by Mohamed-Hacene** [comment]
Thanks for your report @CyberPoly1000, we are aware of this display problem which will be fixed asap, I will link the PR during the day so that you can test it for your case too.

**Comment by Mohamed-Hacene** [comment]
Ok @CyberPoly1000, I opened a PR #449 for this issue where the rendering should be fixed. You can either test it now to confirm or wait that we merge it to test it on main branch. 

Thanks for your help !

**Comment by ab-smith** [comment]
The duplication of the legend was also annoying and has been fixed as well, while lowering the font.
