### ISSUE TITLE
Unexpected error occured while upgrading a still present library

### ISSUE THREAD

**Issue by panic34fr** [intuitem/ciso-assistant-community#471]
**Describe the bug**
While a library is still present or still active, you can't upgrade it or disable it

**To Reproduce**
1. Go to 'Extra'
2. Click on 'Libraries'
3. Select 'Libraries Store' Tab
4. Scroll down to bootom of page
5. Choose a YAML file to import (one of a library still imported)
6. Click on 'Upload' button
7. See error

**Expected behavior**
It could purpose to upgrade or overwrite a still present file

**Screenshots**
A message box (in red) with this notice is opened : "An error occurred during the importation of your library."

**Environment (please complete the following information):**
 - Device: PC laptop
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 124

**Additional context**
This issue still appears for an installed library (one activated in Libraries Store) you want to uninstall.
The message is some different but root cause is similar (no overwrite on disk) : "Unexpected error occurred while deleting the library."

**Comment by panic34fr** [comment]
![image](https://github.com/intuitem/ciso-assistant-community/assets/4822363/7b30bd49-b4e1-4d67-b02f-074e3324f367)

**Comment by ab-smith** [comment]
hello @panic34fr ,

Thanks for the feedback. Can you confirm which version you're using? 

Also, for your experimentation, are you sure that the new file has a different version? Backend logs can help identify the root cause.

<img width="812" alt="image" src="https://github.com/intuitem/ciso-assistant-community/assets/11318384/156d1518-4a22-4996-b20e-8e6d35caa4a1">

**Comment by panic34fr** [comment]
Hi,
I just tested it now, even if i change the version number, it does persist.
My current version is 1.3.4.

Thank you

**Comment by panic34fr** [comment]
Just tested in 1.3.5 : it seems to be fixed
Thanks

**Comment by ab-smith** [comment]
You’re welcome @panic34fr,
make sure to star the repo to stay up to date with all the evolutions 🤗
