### ISSUE TITLE
Erreur d'export d'audit / Error on audit export -- community edition;

### ISSUE THREAD

**Issue by devoyon** [intuitem/ciso-assistant-community#473]
**Describe the bug**
Runiing multiple audits on same fraworks but on different projects.
When exporting audit you have a zip downloaded on your pc. The zip contain the wrong audit (in fact always provide the first audit of the framework done on CISO)

**To Reproduce**
1. Create 2 projects.
2. On both projects run an audit (used ANSSI hygienne)
3. On both, complete or fill the dedicated audits
4. Goes on second project -> audit -> export results
5. You get the export of the audit on the first project...

**Expected behavior**
Just having the export of the audit we are on :)

**Environment (please complete the following information):**
Ciso 1.3.3 build ce6ffaf
Community edition under docker under WSL2 (W11)
Chrome Version 124.0.6367.208 (Build officiel) (64 bits)

**Comment by Mohamed-Hacene** [comment]
Hi @devoyon, 

I tried to reproduce your error twice, but I always got the right export. I'm going to run more tests to be sure I'm not missing something. Could you try to reproduce that behavior on your side with another framework ?

**Comment by Mohamed-Hacene** [comment]
Ok, I was finally able to reproduce that behavior. Thank you very much we will investigate, you can follow the fix on the linked branch or wait for the PR.

**Comment by Mohamed-Hacene** [comment]
The PR #476 should fix this issue, @devoyon could try to reproduce your case on the fix branch ?
