### ISSUE TITLE
Error 500 when the session expires

### ISSUE THREAD

**Issue by tovam** [intuitem/ciso-assistant-community#475]
**Describe the bug**
After not using the app for a while (I guess when the auth cookie expires), opening a page gives an error 500.
Only after manually reloading the error page we are redirected to the login page

**Expected behavior**
An auto-redirect to the login page

**Comment by ab-smith** [comment]
hey @tovam 
It has been improved on multiple pages to send back to the login instead. Can you indicate the click path that you're doing to get that?
thank you

**Comment by tovam** [comment]
It was all the pages I tried but I didn't keep the exact pages that were impacted
I'll try a few ones and will report back here

**Comment by ab-smith** [comment]
with the recent optimizations and the increase of session timeout, most of these equivalent issues have been absorbed, unless there is an actual bug. we will open dedicated ones accordingly.
