### ISSUE TITLE
Cannot clone the repo

### ISSUE THREAD

**Issue by ITMaya** [intuitem/ciso-assistant-community#479]
Hi,

When I try to run the following command:
`git clone git@github.com:intuitem/ciso-assistant-community.git`

I have this result:
```
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

```

Do we need to ask for access? Thanks for your help.

**Comment by ab-smith** [comment]
Hello,
this is because you haven’t set your ssh key on GitHub. To proceed with that, you need to generate an ssh pair and import the public one to your github profile. 

alternatively, you can switch to https using:

git clone https://github.com/intuitem/ciso-assistant-community.git
