### ISSUE TITLE
Add a field "Guidance" to the Audit control form

### ISSUE THREAD

**Issue by joostdaem** [intuitem/ciso-assistant-community#490]
**Problem statement**
In addition to the fields Status, Score and Observation on the audit controls it would be of added-value to have additional field "Guidance" that can be used to put guidance content for the auditor. This field could then be used as a reference during the audit.

**Comment by eric-intuitem** [comment]
Indeed, we have a field called "annotation" in the data model that is not yet rendered in the frontend, and can play that role.
