### ISSUE TITLE
Ability to clone an existing audit

### ISSUE THREAD

**Issue by joostdaem** [intuitem/ciso-assistant-community#491]
**Problem statement**
It would be great to have the ability to clone an existing audit

**Expected behavior**
Have the option to clone the original audit with or without the observations of the original audit.

**Mock**
If applicable, add screenshots to help explain the expectation.

**Additional context**
This can help planning a periodic audit or repeat an existing one.

**Comment by eric-intuitem** [comment]
This feature will be available soon, along with the mapping feature.

**Comment by CyberPoly1000** [comment]
Similar to this issue : https://github.com/intuitem/ciso-assistant-community/issues/376

**Comment by ab-smith** [comment]
Covered in #185 that got merged today
