### ISSUE TITLE
Audit status label is sometimes not displayed in the audit page

### ISSUE THREAD

**Issue by tovam** [intuitem/ciso-assistant-community#529]
**Describe the bug**
Color labels with audit status are not displayed in some situations, depending on the previous page displayed (?)

**To Reproduce**
1. Go to https://localhost:8443/frameworks (the bug is triggered from some pages, but not from others)
2. Click on Compliance > Audits
3. No labels
4. Reload the page
5. Labels are shown

**Comment by ab-smith** [comment]
To reproduce this consistently:
- log out and log in
- go to organization then Domains
- refresh the page 
- go to compliance then Audits
- you'll see the issue of status badges not displayed 
- refresh the page, they will appear
