### ISSUE TITLE
ERR_SSL_PROTOCOL_ERROR when connecting to CISO Assistant

### ISSUE THREAD

**Issue by cota44ur** [intuitem/ciso-assistant-community#547]
Hi,

I'have installed CISO Assistant this morning. All did well, the 3 docker images are running correctly.
However, wham I've tried to connect the server from my browser (edge and firefox), I have an SSL Error : "ERR_SSL_PROTOCOL_ERROR".

It's written in the documentation 
"SSL Warning : Given that Caddy is using a self-signed certificate, your browser will mention a warning that you can accept and continue".

With the lastest version of Egde or Firefox browser we cannot accept and continue.

Some more information (OpenSSL is a bit old) :
[toto@serversec ~]$ ./docker-compose version
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019

Thank you for your help
Regard,
Etienne

**Comment by ab-smith** [comment]
hey @cota44ur , did you use the standard docker-compose and login in using https://localhost:8443/ ?

**Comment by cota44ur** [comment]
Bonjour Abder, j'ai mis le FQDN et tout fonctionne ! merci beaucoup
