### ISSUE TITLE
Add support for CSA CAIQ 

### ISSUE THREAD

**Issue by cota44ur** [intuitem/ciso-assistant-community#555]
Hi,

I would like to add to CISO Assistant librairies 2 new framworks : CCM and CAIQ from CSA.

Both .XLS et YAML files are available on CSA web site : 
https://cloudsecurityalliance.org/research/cloud-controls-matrix

1. Is it possible to add these 2 new frameworks in the next release ?
2. How is it possible to add custom frameworks (that would not necessarily interest the community) ?

Thank you for your great job ;-)

**Comment by ab-smith** [comment]
Hello, thank you for the feedback,
the CCM is actually supported but with an extra manual action given the license restriction, checkout the instructions on tools folder;
we can do the same for CAIQ

**Comment by ab-smith** [comment]
We've added the the CAIQ part as annotation over the CCM to avoid duplication :)
