### ISSUE TITLE
Evidence not downloadable

### ISSUE THREAD

**Issue by CyberPoly1000** [intuitem/ciso-assistant-community#558]
**Describe the bug**
It is not possible to retrieve a file that has been given as an evidence's attachment (JSON or PNG). 

**To Reproduce**
1. Upload a file in the evidence
2. Try to download the file 
OR 
1. In an audit, give a evidence with the file to a control
2. Export the audit in ZIP
3. The file is not in the attachments folder

**Expected behavior**
The file should be downloadable 

**Screenshots**
![image](https://github.com/intuitem/ciso-assistant-community/assets/52451277/eac2e048-3101-491a-bcbb-7137ed2914d0)
After clicking "download" : 
![image](https://github.com/intuitem/ciso-assistant-community/assets/52451277/f10b10eb-7d8c-403d-a908-5007fc396d4e)

**Environment:**
 - Version 1.42.0 build 8b91f9dd

**Additional context**
I did not upload the file myself so I can't reproduce with this exact file. It has been uploaded in previous version of the app, since the last release I can upload then download file. This error is annoying :p

**Comment by CyberPoly1000** [comment]
It's like no attachments were found : 
![image](https://github.com/intuitem/ciso-assistant-community/assets/52451277/3c2294ac-4648-4041-b0f0-26e300e3a9ba)

It is maybe a problem from our side, the attachments have maybe been deleted in the DB. Where are the attachments located in the DB ?

**Comment by CyberPoly1000** [comment]
Don't think this is related, as the files were simple images and names were basics and UTF8

**Comment by ab-smith** [comment]
> It is maybe a problem from our side, the attachments have maybe been deleted in the DB. Where are the attachments located in the DB ?

hello, the attachments in the standard setup are in ./db/attachments/ subfolder and filenames referenced in core_evidence

**Comment by ab-smith** [comment]
@CyberPoly1000 have you checked that the files are still there?

**Comment by CyberPoly1000** [comment]
Hi guys, I've just checked and the files are not in the attachments folder. It seems that someone deleted them manually. Sorry for the bother, it is an issue from my side.

**Comment by ab-smith** [comment]
Thanks for confirming @CyberPoly1000 
We didn’t want to add too much dependencies on the community version to make it simpler to install but we will probably move storage later on to an object storage with minio or equivalent.
