### ISSUE TITLE
Polish Language

### ISSUE THREAD

**Issue by AndrzejRPiotrowski** [intuitem/ciso-assistant-community#573]
**Describe the bug**
Version 1.5.1 has issue, cannot select Polish Language 

**Environment (please complete the following information):**
 - Device: PC
 - OS: Windows 11
 - Browser : Chrome / Firefox
 - Version : Version 128.0.6555.0 / 127.0.1

**Additional context**
It was working on my Branch, after change with sync I cannot access

**Comment by ab-smith** [comment]
How are you testing this? if you're in dev mode, you might want to stop the frontend and restart it.
If you're still stuck we can chat about it over discord to assist you.

**Comment by ab-smith** [comment]
Try to run the app from the main branch of the main repo using `docker-compose.sh` or make sure your fork is up to date, most likely, your fork has a conflict as some params were missing:

<img width="770" alt="image" src="https://github.com/intuitem/ciso-assistant-community/assets/11318384/245e3b62-cdee-485d-a389-0a59a0be4fc3">

<img width="287" alt="image" src="https://github.com/intuitem/ciso-assistant-community/assets/11318384/04a34c47-ba75-4feb-916f-929b84176f89">

We can check that out over Discord 🤗
