### ISSUE TITLE
Use clipboard to paste evidence

### ISSUE THREAD

**Issue by nka11** [intuitem/ciso-assistant-community#618]
I want to paste a screenshot in the evidence form.

Right now, to use a screenshot as evidence, I must, after taking the screenshot, save it as a file and then got to ciso assistant and find the file to load it.
I won't need to save all these file and clean them after from my workstation if the screenshot could just be pasted in some field.

That would save a lot of time and useless manipulations

I don't know about the browser API capabilities to paste files, or parts of a spreadsheet content for example, but that could also be amazing to fill the evidence, to have a very smart clipboard paste event handler.

As the task itself of collecting evidence is not the best experience, makes the tool's experience the less harsh would add a nice value.

**Comment by ab-smith** [comment]
It’s a cool suggestion and the best thing is that it’s already available :)
on the evidence modal (window), you can press tab to get the hover on file select and past your screenshot

**Comment by nka11** [comment]
Cool, so it just needs to be readable somehow in the modal's ux.
A button with tooltip "Paste screenshot as attachment" could also be à good experience

**Comment by ab-smith** [comment]
Thank you for the feedback @nka11 , the message has been improved in #619  and will be in the next release.
You can star the repo and activate the watch mode to get notified when it's the case 🤗
The doc has been updated as well to reflect that.
