### ISSUE TITLE
Click outside "input area" is loosing everything

### ISSUE THREAD

**Issue by drummbelbummel** [intuitem/ciso-assistant-community#623]
**Describe the bug**
I am using Firefox on a local installation. If i e.g. add an asset the asset form is opening. I am filling out but clicking on the window outside the form. This is destroying all my input. This issue seems to be in every situation where a "form" is opened.

**To Reproduce**
go to "CONTEXT" / "Assets"
click on "+ Add asset"
fill in some data
click outside the form

**Expected behavior**
The form opened shall not disappear if clicking outside hence loosing the data

**Screenshots**
guess this is self explaining

**Environment (please complete the following information):**
Docker Desktop
Firefox 127.0.2 on Windows 11 23H2
NoScript AddOn but no blocked scipts

**Additional context**

**Comment by ab-smith** [comment]
The is the standard behaviour of Modals @Mohamed-Hacene ; what can we do to improve this? Detect changes and display warnings for instance?

**Comment by Mohamed-Hacene** [comment]
Yes, I think the best solution is to save the state of the inputs to recover the form as we left it and keep modals default behavior

**Comment by drummbelbummel** [comment]
thank you for taking care of this issue...

**Comment by eric-intuitem** [comment]
Fixed in v1.6.1
