### ISSUE TITLE
Filters are not consistent

### ISSUE THREAD

**Issue by ab-smith** [intuitem/ciso-assistant-community#624]
The numbers are not consistent as in here:

<img width="1231" alt="image" src="https://github.com/intuitem/ciso-assistant-community/assets/11318384/09113367-2958-434f-9fb7-371504ebffbb">

and sometimes it even skips some values (I have 3 audits):
<img width="846" alt="image" src="https://github.com/intuitem/ciso-assistant-community/assets/11318384/93d02622-5913-45dc-935a-6def0745b6ac">

**Comment by nas-tabchiche** [comment]
Fixed in #631, will be merged on main today hopefully
