### ISSUE TITLE
Enhanced status tracking of Audits

### ISSUE THREAD

**Issue by Lithilion** [intuitem/ciso-assistant-community#632]
**Problem statement**
I want to be able to display the status of the requirement assessment compared to the policy (compliant, non-compliant, partially compliant) and the status compared to the work status (to-do, in progress). The tool only lets me choose on of these stati.

**Expected behavior**
I want to choose two stati. One that thats the compliantness and one that states the progress status; e.g. The assessment A is "partially compliant" and "in progress". The assessment B is "compliant". The assessment C is "partially compliant" and "To-do". Additionally, I would like a status "Review required/requested".

**Comment by Lithilion** [comment]
I'm not sure, I understood the question.

![Screenshot from 2024-07-10 17-28-28](https://github.com/intuitem/ciso-assistant-community/assets/173987040/74691752-37d4-48fe-8620-443fef129566)
An audit has this view at the moment. I want to enhance this view, to be able to display two stati. e.g. "To Do" and "partially compliant" in the same row, for the same requirement assessment.

**Comment by ab-smith** [comment]
Hello @Lithilion 
Sorry this got buried down, I believe it was a temporary regression that got fixed a while back:
<img width="2080" alt="image" src="https://github.com/user-attachments/assets/5100972e-faf8-4c82-8f80-61b110b9b7ce" />

Let me know if you have other questions or suggestions:)
