### ISSUE TITLE
Use ACR / AKS to run CISO assistant

### ISSUE THREAD

**Issue by vegazbabz** [intuitem/ciso-assistant-community#635]
**Problem statement**
The current guidelines for running the solution "remote" is limited.
It would be very beneficial if the solution could run (and it probably can) in e.g. Azure public cloud. The guidelines seems to be missing for this.

**Expected behavior**

**Mock**
If applicable, add screenshots to help explain the expectation.

**Additional context**

**Comment by fdicarlo** [comment]
Tried to install using AKS on Azure, it is quite expensive, I am happy to share the step-by-step guideline I wrote.

Ideally, to keep cost under control, better solution is to use:

**Option 1: Azure Container Instances (ACI)**
Azure Container Instances (ACI) allow you to run containers without managing VM infrastructure, which can be more cost-effective for non-critical workloads. You can deploy your Docker images directly to ACI. ACI is a pay-per-second model, and you only pay for the compute resources you use. Example commands to deploy a container to ACI:

```
az container create --resource-group <YourResourceGroup> --name backend-container --image <YourACRName>.azurecr.io/ciso-assistant-backend:latest --cpu 1 --memory 1 --registry-login-server <YourACRName>.azurecr.io --registry-username <YourACRUsername> --registry-password <YourACRPassword>
az container create --resource-group <YourResourceGroup> --name frontend-container --image <YourACRName>.azurecr.io/ciso-assistant-frontend:latest --cpu 1 --memory 1 --registry-login-server <YourACRName>.azurecr.io --registry-username <YourACRUsername> --registry-password <YourACRPassword>
az container create --resource-group <YourResourceGroup> --name caddy-container --image <YourACRName>.azurecr.io/caddy:2.7.6 --cpu 1 --memory 1 --registry-login-server <YourACRName>.azurecr.io --registry-username <YourACRUsername> --registry-password <YourACRPassword>

```
To consider using Azure Storage or Azure SQL Database.

**Option 2: Use Azure App Service for Containers**
Azure App Service provides a fully managed platform for deploying and scaling web apps, APIs, and mobile backends. You can deploy each of your containers (backend, frontend, and caddy) as individual web apps within an App Service Plan. Example commands to deploy a container to Azure App Service:

```
az appservice plan create --name <YourAppServicePlan> --resource-group <YourResourceGroup> --sku B1 --is-linux
az webapp create --resource-group <YourResourceGroup> --plan <YourAppServicePlan> --name backend-app --deployment-container-image-name <YourACRName>.azurecr.io/ciso-assistant-backend:latest
az webapp create --resource-group <YourResourceGroup> --plan <YourAppServicePlan> --name frontend-app --deployment-container-image-name <YourACRName>.azurecr.io/ciso-assistant-frontend:latest
az webapp create --resource-group <YourResourceGroup> --plan <YourAppServicePlan> --name caddy-app --deployment-container-image-name <YourACRName>.azurecr.io/caddy:2.7.6

```

Configure Scaling and Cost Management:

1. Choose a lower-tier App Service Plan (like B1 or B2) to reduce costs.
2. Configure autoscaling rules to scale down during off-peak hours.

**Comment by fdicarlo** [comment]
> Great guide. Appreciated!
> 
> Maybe doc pages could be open to edit for community help to improve via pull-requests, such adding this guide directly.

I wrote something on #830 , problem is I am getting an error and trying to get CISO Assistant people (or users) to help

**Comment by ab-smith** [comment]
Helm chart is now supported and covers this
