### ISSUE TITLE
partage web access to lan

### ISSUE THREAD

**Issue by Lb59** [intuitem/ciso-assistant-community#637]
How to partage web access on my lan with docker installation ?
Thank you

**Comment by Lb59** [comment]
Ok it s good.
Please, tell me what is the default account ?

**Comment by Lb59** [comment]
how to automatically start docker when the server starts ? 
thank you

**Comment by eric-intuitem** [comment]
Please have a look here: https://docs.docker.com/config/daemon/start/

**Comment by ab-smith** [comment]
All good @Lb59 ?

**Comment by ab-smith** [comment]
Closing the ticket and feel free to re-open it if you have further questions.
