### ISSUE TITLE
test cases for cloud for compliances

### ISSUE THREAD

**Issue by rezcommltd** [intuitem/ciso-assistant-community#646]
Hi,

does ciso assistant has test cases for cloud for compliances?

**Comment by cota44ur** [comment]
Hi,
CSA provide CCM and CAIQ questionnaires but they are subject to licensing.
You can get CCM/CAIQ for free and integrate them in CISO Assistant librairies throught python scripts.
Regards

**Comment by ab-smith** [comment]
Hello @rezcommltd 
is your question about CSA frameworks or how to get the outputs from a cloud compliance scanning tool to CISO Assistant?

**Comment by ab-smith** [comment]
Closing it for now and feel free to reopen it, if you have more info 😉
