### ISSUE TITLE
Filters are not working

### ISSUE THREAD

**Issue by AndrzejRPiotrowski** [intuitem/ciso-assistant-community#653]
**Describe the bug**
Filters not loading

**To Reproduce**
1. Go to context - > Threats
2. Click on Filter
3. Something appears as white box
4. Disappears without touching

**Expected behavior**
Should appear filter

**Screenshots**

![image](https://github.com/user-attachments/assets/0de9b42d-0279-460a-9e03-991af6a73b17)

![image](https://github.com/user-attachments/assets/abbb5011-fa4b-44c1-9503-95e886fb135a)

**Environment (please complete the following information):**
 - OS: Windows
 - Browser : Chrome/Firefox
 - CiSO Version : 1.6.1 

**Additional context**

**Comment by ab-smith** [comment]
Related to #624

**Comment by nas-tabchiche** [comment]
Thanks for the input. This is fixed by #631 and will be merged on main today, most likely.
