### ISSUE TITLE
Can't import own library for audits

### ISSUE THREAD

**Issue by aminerais** [intuitem/ciso-assistant-community#661]
I can't import my own library, either by using the importing tool at the bottom of the libraries page or by adding the file to the backup (I restarted the server after adding it, and I also tried building the Docker backend with an image where the .yaml file is added)

**Comment by ab-smith** [comment]
Hello @aminerais and thanks for reaching out,
How did you create the yaml file? Directly or through the convert script from an excel sheet? On the backend logs you usually would see an error message with more info.

Do you mind sharing the file in a DM through Discord or email (contact@intuitem.com) ?

**Comment by aminerais** [comment]
Hello ab-smith, Thanks for the fast response.

I just sent it to you through email :)

**Comment by ab-smith** [comment]
Great, I've fixed your Excel sheet and you should be fine 🤗
Don't forget to Star the GitHub repository for updates. You can even consider submitting a PR with this file if you're up to it.
Warm regards,
