### ISSUE TITLE
Export Audit as CSV and Excel

### ISSUE THREAD

**Issue by ab-smith** [intuitem/ciso-assistant-community#671]
Include assessable and non assessable items, maintain the framework structure, have the compliance status, progress and score if any, applied control with it's status.

|ref_id|name|description|compliance|Progress|Maturity|applied_controls|
|---|---|---|---|---|---|---|
|---|---|---|---|---|---|[planned] abc \n [active] xyz|

**Comment by eric-intuitem** [comment]
compliance -> Result
Progress -> Status
Maturity -> Score
