### ISSUE TITLE
ISO13485 (EU MDR)

### ISSUE THREAD

**Issue by AndrzejRPiotrowski** [intuitem/ciso-assistant-community#673]
**Problem statement**
I want to use ISO13485

**Additional context**
Is there any other alternative ?

**Comment by eric-intuitem** [comment]
@AndrzejRPiotrowski the simplest solution is to make you own private library, by writing your own excel file and converting it. There are many examples in the tools/ directory. Please ask us in PM on Discord if you need assistance.
