### ISSUE TITLE
Risks not displayed in matrix view for urn:intuitem:risk:matrix:critical_risk_matrix_5x5 when language set to French

### ISSUE THREAD

**Issue by smonfort-cacd2** [intuitem/ciso-assistant-community#692]
The risks are not displayed in the matrix view when using the critical_risk_matrix_5x5 in French. Risks are correctly displayed when switching the language to English.

**To Reproduce**
1. Set current lang to French
2. Create a risk assessment using critical_5x5 matrix
3. Add a risk scenario and set the current risk level
4. Go back to the risk assessment page to display the risk matrix
5. The risk is not displayed in the matrix
6. Switch lang to English
7. The risk is then displayed

**Expected behavior**
The risk should appear in the matrix view when lang is set to French.

**Screenshots**
When lang set to English
<img width="597" alt="image" src="https://github.com/user-attachments/assets/1137abf1-d39f-4ba2-a8fd-5682329f4715">

When lang set to French
<img width="575" alt="image" src="https://github.com/user-attachments/assets/8dce7f64-229b-48f4-b299-683bc6be4554">

**Environment (please complete the following information):**
 - Device: MacBook Pro M1
 - OS: 14.5 (23F79)
 - Browser Brave v1.68.131
 - Version v1.6.3

**Comment by ab-smith** [comment]
@eric-intuitem  related to recent change?

**Comment by nas-tabchiche** [comment]
Fixed with #694

**Comment by smonfort-cacd2** [comment]
Thanks for your quick fix 🙏
