### ISSUE TITLE
Impossible to edit existing applied control

### ISSUE THREAD

**Issue by CyberPoly1000** [intuitem/ciso-assistant-community#732]
**Describe the bug**
When editing an existing applied control, an error appears in the name of the control stating "... is already used in this scope. Please choose another value."

**To Reproduce**
1. Go to 'Applied controls'
2. Click on edit a control
3. Modify a field (except the name)
4. Try to save the change and see the error in the name field

**Expected behavior**
Should be able to edit already existing control. 

**Screenshots**
![image](https://github.com/user-attachments/assets/b71398e8-9590-4afa-9f53-d14f152fc2c4)

**Environment (please complete the following information):**
 - Browser Brave
 - Version ![image](https://github.com/user-attachments/assets/28780f54-c045-430f-a8a9-14313fa3fa8a)

**Comment by ab-smith** [comment]
hi,
The protection on the name is on purpose to keep clarity since it's used at multiple positions. Try again using a unique name. 
I'm on 1.6.4 and cannot reproduce it. Tested fixing typo in name, switching CSF function and looks ok

**Comment by CyberPoly1000** [comment]
Hi, I don't understand why I should rename my applied control ? I just want to add a link and a description to this already existing applied control, changing the name is not relevant in this case. 
As it is displayed, the name already exists in my scope, which is accurate because it is the same applied control. I don't have another applied control that has the same name. So this seems like a bug to me

**Comment by ab-smith** [comment]
If you're certain that you don't have another applied control with the exact name then it's definitely a bug. We've found an issue on the link field where you can't save the applied control if it was set then unset and the fix is released in v1.6.6;
let me know @CyberPoly1000

**Comment by CyberPoly1000** [comment]
I confirm I don't have any control with the same name. Ok then, I'll close the issue awaiting the fix.
