### ISSUE TITLE
Library - 

### ISSUE THREAD

**Issue by jschav88** [intuitem/ciso-assistant-community#765]
**Problem statement**
On Excel, is it possible to add specifics answers into a library for some questions before use `convert-library.py`. For example, for a control line, i'd like to be able de choose between "No,Yes100%,Yes80%,Yes60%,Yes40%,Yes20%" or "Yes - once a day, Yes, one a month, Never" etc. 

If its not possible, could you add this feature? 

Thanks

**Comment by ab-smith** [comment]
Hello @jschav88 
thank you for reaching out. We don’t have such feature as part of the conversion process but if the intent is to get a percentage as scoring, you can already do that for frameworks that don’t have an explicit scoring system. To experiment that, try an audit with iso 27001 and enable the scoring for an item to get the slider.
the second part that you’ve mentioned is kind of strange as this will be about the frequency of a task and not it’s completion or scoring, maybe you have something specific in mind and we can discuss it over Discord (FR/EN).
regards,

**Comment by ab-smith** [comment]
Hello @jschav88 ,
The new feature of supporting questions within requirements could be an option for your need. Take a look at the Adobe framework or CMMC and hopefully it can fit your specific case.
Regards
