### ISSUE TITLE
Microsoft Entra ID SSO issue

### ISSUE THREAD

**Issue by Loknath-Das** [intuitem/ciso-assistant-community#783]
**Problem statement**
As of last week, SSO using Microsoft Entra ID was working for me, while trying to setup ciso-assistant for production use, I'm getting error 404 as soon I click on sign in using sso. I have configured everything as per the documentation. 

![image](https://github.com/user-attachments/assets/f3329f31-210a-4485-9290-07c159bef4bf)

<img width="697" alt="image" src="https://github.com/user-attachments/assets/f3ba079c-587e-41ac-9a51-f4898fc01fee">

**Comment by ab-smith** [comment]
@Mohamed-Hacene could it be related to the adjustment done for Google workspace?

**Comment by Mohamed-Hacene** [comment]
Normally not, it works fine on my side. It seems to be a specific error on the instance because there should be a toast with the error message coming from the SSO. @Loknath-Das, what did you change between your environment and thr production one ?

**Comment by Loknath-Das** [comment]
Hi @Mohamed-Hacene there's no change between environment, all the configuration is exactly same.

**Comment by Mohamed-Hacene** [comment]
Ok thanks, are your on a cloud instance or deploying CISO Assistant by yourself ?
If you're deploying it, could you share your backend/frontend containers logs when you try to connect with SSO ?

**Comment by Loknath-Das** [comment]
@Mohamed-Hacene I'm deploying CISO Assistant by myself, here's the logs

<img width="947" alt="image" src="https://github.com/user-attachments/assets/910113b6-a17c-41a2-b0d9-960e8cc3ec47">

**Comment by Mohamed-Hacene** [comment]
Ok as I thougth, it is not related to SSO, it is bad redirection after a successful login. I don't know yet why you're redirected to that url.
To check this hypothesis, can you log yourself with SSO, once you get the 404 error just remove `//sso/authenticate/...` from your url and you should be connected correctly to your instance

**Comment by Loknath-Das** [comment]
@Mohamed-Hacene  still it's same.
![image](https://github.com/user-attachments/assets/bb4295bc-4eb4-40dd-8538-c85342b63a60)

**Comment by Mohamed-Hacene** [comment]
You need to remove everything after your base url, here the id is not a know path on the application (which is totally normal)

**Comment by Loknath-Das** [comment]
Hi, @Mohamed-Hacene the issue still persist, even if I remove all of it after //sso/authenticate and try to do sso again, I still get the Error 404

**Comment by Mohamed-Hacene** [comment]
Ok, do you access ciso assistant if your remove the bad path before retrying to login ?

**Comment by Loknath-Das** [comment]
Yes, I get to access ciso assistant if I remove the bad path and when I click on sso again, I get the same error

**Comment by Loknath-Das** [comment]
Yeah, upon login without sso I am able to authenticate. Error is only when I try to login using sso

**Comment by Mohamed-Hacene** [comment]
Ok I think I've found why you get this error, inside your Microsoft Entra application configuration the `Relay Status` field had a typo:
![image](https://github.com/user-attachments/assets/5377edef-4f2e-40d0-95af-7803a6daead1)
The double slash at the end of the url also redirects me to the same bad url as you. Could you check this field to be sure the slash is not doubled ?

**Comment by Loknath-Das** [comment]
Hi @Mohamed-Hacene  Really Appreciate your help here. If I'm not wrong this is an optional setting, right? As I have not added any URL in the relay status. 
For now, I have added the base URL in the relay status. still the error remains the same to me.

**Comment by Loknath-Das** [comment]
Hi @Mohamed-Hacene Thank you for the help, I have fixed this issue. it seems the issue was within the configuration file "docker-compose.yml" where extra slash was added in the URL, which was resulting in this //sso/authenticate/...

**Comment by Mohamed-Hacene** [comment]
Ok so the typo was in the `docker-compose.yml` file, well done! I don't know why I didn't notice the double slash earlier :)

Thanks for the issue, it helps us a lot to improve our support.
