### ISSUE TITLE
New Policies issue

### ISSUE THREAD

**Issue by ionutmocanita** [intuitem/ciso-assistant-community#790]
**Describe the bug**
When I try to add a new policy, nothing apair.

**To Reproduce**
1. Go to '/policies'
2. Click on Add Policy

**Expected behavior**
Open new policy tab

**Environment (please complete the following information):**
 - Device: Esxi
 - OS: Ubuntu 22.04 LTS
 - Browser firefox

**Comment by ionutmocanita** [comment]
![image](https://github.com/user-attachments/assets/6a1ea335-8245-4cbc-9397-6e2ca6495469)

**Comment by ab-smith** [comment]
thank you @ionutmocanita for reporting this, cause identified and the fix will be on the next release

**Comment by ionutmocanita** [comment]
Thanks @ab-smith for fast feedback! Happy to see in the next release.
Cheers!
