### ISSUE TITLE
CLI for batch actions

### ISSUE THREAD

**Issue by ab-smith** [intuitem/ciso-assistant-community#800]
Hello,
As discussed with many users, the CLI could be nice addition for batch operations to avoid too many clicks. We've started this poll on Discord to shape and identify the most relevant cases as a starting point:

https://discord.com/channels/1155083727932764190/1210262391091241132/1280479796517797983  

Thank you

**Comment by brunoR1000** [comment]
This might help you
https://bit.ly/3yXXzbX
Passcode: d5kp14h
You must have gcc compiler installed
