### ISSUE TITLE
Unauthorized: /api/applied-controls/todo/

### ISSUE THREAD

**Issue by EmilienPer02** [intuitem/ciso-assistant-community#810]
**Describe the bug**
Impossible to login after docker-compose installation. 
Error form backend : Unauthorized: /api/applied-controls/todo/

**To Reproduce**
1. install using docker-compose up
2. go to login page
3. log user superuser credentials
![image](https://github.com/user-attachments/assets/9e421a75-89e7-4869-9ca3-ed4e82d14465)

**Comment by Mohamed-Hacene** [comment]
Hi @EmilienPer02,

What do you get on your screen when you try to login ?

**Comment by JosephSaliba01** [comment]
I also seee the frontend error that @EmilienPer02 showed in picture. I think that is related to the backend not returning data from the urls requested due to the unexpected 401.

**Comment by eric-intuitem** [comment]
To answer your question, it is normal that you can't see the API calls on Chrome debug tool, because the API calls are done by the frontend, not by the navigator. The only exception is for SSO.

**Comment by JosephSaliba01** [comment]
In the end, my issue was fixed by implementing SSL.

This issue can be closed.

**Comment by Itraore86** [comment]
@JosephSaliba01 Hello, please how to implementing SSL
