### ISSUE TITLE
Bigger URL size

### ISSUE THREAD

**Issue by Pioupuch** [intuitem/ciso-assistant-community#836]
**Problem statement**
I want to be able to add a potentially long URL for evidences and any other URL link but it seems that Django and the URLField in the models is not more than 200 characters. Then I cannot add SharePoint or drive big links to the URL fields.

**Expected behavior**
Is it possible to override and add extra Characters. Based on the RFC 2616, their is no specific limit to the URI but the URL can be maximum 2083 characters in most browsers.

**Comment by ab-smith** [comment]
will be available in the next release.
