### ISSUE TITLE
Failed loading ESRS library as a Domain Manager

### ISSUE THREAD

**Issue by casadobarragan** [intuitem/ciso-assistant-community#853]
**Describe the bug**
When trying to load a library as Domain Manager of a specific domain, it gives Error500.

**To Reproduce**
1. Loggin as a Domine Manager User
2. Go to 'Extra - Libraries'
3. Select any library.
4. Click on the "Load Library" button.
5. See error500
<img width="1423" alt="Captura de pantalla 2024-09-20 a la(s) 3 31 17 p  m" src="https://github.com/user-attachments/assets/c80f87a4-12a1-4dea-8b28-434c0cca6583">

**Expected behavior**
The library should load without any issues and be reflected in the respective section of the Domain, e.g. risk matrices, threats, etc.
**Screenshots**

**Environment (please complete the following information):**
 - Device: Macbook pro
 - OS: MacOS Sonomoa 14.6.1
 - Browser Chrome and Firefox
 - Version: Chrome Versión 129.0.6668.58 and Firefox 130.0 (64-bit)

**Comment by ab-smith** [comment]
thank you @casadobarragan The problem can indeed be reproduced and is specific to this library. We'll take a look and get back to you

**Comment by ab-smith** [comment]
in the meantime @casadobarragan try to import another ESRS library and load this one to see if it unlocks the situation

**Comment by casadobarragan** [comment]
thank you @ab-smith for the support. I tried to load other libraries and it is not possible. I get the same error with any library I try to load such as Domine Manager 😮

**Comment by eric-intuitem** [comment]
Indeed loading libraries requires administrator right, as libraries are loaded in the global domain. We should make that clear in the UI and not reach the error 500, so this is indeed a bug.
