### ISSUE TITLE
Gitlab or Adobe Common Controls Framework CCF

### ISSUE THREAD

**Issue by mfouad** [intuitem/ciso-assistant-community#868]
**Problem statement**
The [Agile Security Framework - Baseline] Reference controls are not mapped to other Frameworks like ISO27001 or SOC2 
In CCF, Adobe mapped 315 control to 21 industry standard (Framework)
https://www.adobe.com/trust/compliance/adobe-ccf.html

PDF https://www.adobe.com/content/dam/cc/en/trust/pdfs/Open_Source_CCF.pdf
Excel Format https://www.adobe.com/content/dam/cc/en/trust/pdfs/Open_Source_CCF.xls

Gitlab has a forked repo based on CCF
https://gitlab.com/gitlab-com/gl-security/public-gcf/-/tree/master?ref_type=heads

**Expected behavior**

1. Import the CCF library 
2. Reference controls are mapped automatically to frameworks, this way if Applied, you are adhering to the framework.

**Comment by eric-intuitem** [comment]
Very good suggestion, thanks!
We will include de CCF, and provide the mappings.
